# Form implementation generated from reading ui file '/Users/j0z3ph/Repos/Vision/Python/kinect/WinKinect.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(576, 399)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.groupBox_2 = QtWidgets.QGroupBox(parent=self.centralwidget)
        self.groupBox_2.setObjectName("groupBox_2")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.groupBox_2)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.depthLabel = QtWidgets.QLabel(parent=self.groupBox_2)
        self.depthLabel.setFrameShape(QtWidgets.QFrame.Shape.Box)
        self.depthLabel.setText("")
        self.depthLabel.setObjectName("depthLabel")
        self.gridLayout_3.addWidget(self.depthLabel, 0, 0, 1, 1)
        self.gridLayout.addWidget(self.groupBox_2, 0, 1, 1, 1)
        self.groupBox = QtWidgets.QGroupBox(parent=self.centralwidget)
        self.groupBox.setObjectName("groupBox")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.groupBox)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.rgbLabel = QtWidgets.QLabel(parent=self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.rgbLabel.sizePolicy().hasHeightForWidth())
        self.rgbLabel.setSizePolicy(sizePolicy)
        self.rgbLabel.setFrameShape(QtWidgets.QFrame.Shape.Box)
        self.rgbLabel.setText("")
        self.rgbLabel.setObjectName("rgbLabel")
        self.gridLayout_2.addWidget(self.rgbLabel, 0, 0, 1, 1)
        self.gridLayout.addWidget(self.groupBox, 0, 0, 1, 1)
        self.groupBox_3 = QtWidgets.QGroupBox(parent=self.centralwidget)
        self.groupBox_3.setObjectName("groupBox_3")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.groupBox_3)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.skeletonLabel = QtWidgets.QPlainTextEdit(parent=self.groupBox_3)
        self.skeletonLabel.setReadOnly(True)
        self.skeletonLabel.setObjectName("skeletonLabel")
        self.horizontalLayout_2.addWidget(self.skeletonLabel)
        self.gridLayout.addWidget(self.groupBox_3, 1, 0, 1, 2)
        self.gridLayout.setRowStretch(0, 80)
        self.gridLayout.setRowStretch(1, 20)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Kinect"))
        self.groupBox_2.setTitle(_translate("MainWindow", "Depth"))
        self.groupBox.setTitle(_translate("MainWindow", "RGB"))
        self.groupBox_3.setTitle(_translate("MainWindow", "Skeleton"))
