# Form implementation generated from reading ui file '/Users/j0z3ph/Repos/Vision/Python/Pruebas/Ventana.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(426, 233)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.btnInicio = QtWidgets.QPushButton(parent=self.centralwidget)
        self.btnInicio.setGeometry(QtCore.QRect(150, 10, 101, 61))
        self.btnInicio.setObjectName("btnInicio")
        self.lblMensaje = QtWidgets.QLabel(parent=self.centralwidget)
        self.lblMensaje.setGeometry(QtCore.QRect(70, 150, 291, 71))
        self.lblMensaje.setFrameShape(QtWidgets.QFrame.Shape.Box)
        self.lblMensaje.setText("")
        self.lblMensaje.setObjectName("lblMensaje")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.btnInicio.setText(_translate("MainWindow", "Inicio"))
