ifdef OS
	APP = arduino.exe
	EXECCMD = .\arduino.exe
else
	APP = arduino
	EXECCMD = ./arduino
endif
MAIN = arduino.c
SERIALLIB = serial.c
COMPILER = gcc

all: $(APP)
	$(EXECCMD)

$(APP): $(MAIN) $(SERIALLIB)
	$(COMPILER) $(MAIN) $(SERIALLIB) -o $(APP)